Repository lorcalhost/BTB-manager-telegram, pull requests merged in 2021-06, with the labels that each got.

#110 Revert "Enhanced logging of profits to get a deeper understanding/control of …"
  btb_manager_telegram/buttons.py
Labels: bug

#111 Added USD profit calculation for current value button
  btb_manager_telegram/buttons.py
Labels: bug-fix, enhancement

#116 Add python-path parameter
  README.md
  btb_manager_telegram/__main__.py
  btb_manager_telegram/buttons.py
  btb_manager_telegram/handlers.py
  btb_manager_telegram/settings.py
Labels: enhancement
