Repository lorcalhost/BTB-manager-telegram, pull requests merged in 2022-01, with the labels that each got.

#211 Show BTC value lower than 1
  btb_manager_telegram/buttons.py
Labels: type:bug

#213 Bot stats
  btb_manager_telegram/buttons.py
  btb_manager_telegram/handlers.py
  btb_manager_telegram/keyboards.py
  btb_manager_telegram/table.py
  btb_manager_telegram/utils.py
  i18n/en.yml
Labels: type:enhancement, warn:do not merge yet, priority:high, phase:draft

#219 Fix day change BTC
  btb_manager_telegram/buttons.py
  i18n/de.yml
  i18n/en.yml
  i18n/es.yml
  i18n/fr.yml
  i18n/id.yml
  i18n/nl.yml
  i18n/ru.yml
Labels: type:bug, type:enhancement, priority:high, phase:testing

#221 add error handing for bot_stats button
  btb_manager_telegram/buttons.py
  i18n/en.yml
Labels: type:enhancement, type:incompatibility, warn:do not merge yet, priority:high, phase:testing
